name: PR Logs
on: pull_request

jobs:
  logs:
    name: PR Logs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Install requirements
        shell: bash
        run: |
          cargo install --locked cargo-mutants