name: PR Logs
on: pull_request

env:
  TOKEN_DURATION_HOURS: 2
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: localhost
  POSTGRES_DATABASE: auth
  POSTGRES_PORT: 5431
  KEY_DIR: ./keys

jobs:
  logs:
    name: PR Logs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Install requirements
        shell: bash
        run: |
          cargo install cargo-binutils
          cargo install --locked cargo-mutants
          ./genkeys.sh
          rustup component add llvm-tools-preview

      - name: Build mutation testing report
        env:
          KEY_DIR: ./keys
          TOKEN_DURATION_HOURS: 2
        run: ./mutations.sh

      - name: Generate code coverage
        env:
          KEY_DIR: ./keys
          TOKEN_DURATION_HOURS: 2
        run: |
          cargo +nightly tarpaulin --out lcov

      - name: Code Coverage Report
        uses: romeovs/lcov-reporter-action@v0.2.11
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./lcov.info


      - name: Echo Mutation testing report
        id: mutation
        run: |
          report=$(cat mutants.out/missed.txt)
          echo "report<<EOF" >> $GITHUB_OUTPUT
          echo "$report" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send reports to PR comment
        uses: actions/github-script@v6
        env:
          MUTATION: "mutation\n${{ steps.mutation.outputs.report }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 1. Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Coverage Report')
            })

            // 2. Prepare format of the comment
            const output = `
            <details><summary>Mutation testing Report</summary>

            \`\`\`\n
            ${process.env.MUTATION}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.WORKING_DIR }}\`, Workflow: \`${{ github.workflow }}\`*`;

            // 3. If we have a comment, update it, otherwise create a new one
            if (botComment) {
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: output
              })
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
            }
